# Add a Github action, that raises a release PR on merge to qa, uat, main branches, but they will all be different checks.

name: Release PR Workflow

on:
  push:
    branches:
      - dev

jobs:
  release-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple